name = "pwa-cdn"
main = "./dist/index.js"
compatibility_date = "2024-11-19"
account_id = "4d8c0479ab20bad571b1a4d93cf12ab0"
zone_id = "4af564462a548db50ad6f612faa4bfa2"

[vars]
BUCKET_URL = "https://pwac-media.s3.eu-north-1.amazonaws.com"

[[routes]]
pattern = "cdn.pwaforall.dev/*"
zone_id = "4af564462a548db50ad6f612faa4bfa2"
