export const languages = [
  { value: "russian", label: "Русский" },
  { value: "english", label: "English" },
  { value: "german", label: "Deutsch" },
  { value: "french", label: "Français" },
  { value: "spanish", label: "Español" },
  { value: "italian", label: "Italiano" },
  { value: "portuguese", label: "Português" },
  { value: "dutch", label: "Nederlands" },
  { value: "swedish", label: "Svenska" },
  { value: "danish", label: "Dansk" },
  { value: "norwegian", label: "Norsk" },
  { value: "finnish", label: "Suomi" },
  { value: "polish", label: "Polski" },
  { value: "czech", label: "Čeština" },
  { value: "hungarian", label: "Magyar" },
  { value: "greek", label: "Ελληνικά" },
  { value: "romanian", label: "Română" },
  { value: "bulgarian", label: "Български" },
  { value: "croatian", label: "Hrvatski" },
  { value: "slovak", label: "Slovenčina" },
  { value: "slovenian", label: "Slovenščina" },
];

export const categories = [
  { value: "gambling", label: "Гемблинг" },
  { value: "sports_betting", label: "Ставки на спорт" },
  { value: "casino", label: "Казино" },
  { value: "poker", label: "Покер" },
  { value: "lottery", label: "Лотерея" },
  { value: "financial_betting", label: "Финансовые ставки" },
  { value: "esports", label: "Киберспорт" },
  { value: "slots", label: "Слоты" },
  { value: "blackjack", label: "Блэкджек" },
  { value: "roulette", label: "Рулетка" },
  { value: "bingo", label: "Бинго" },
  { value: "live_casino", label: "Живое казино" },
  { value: "fantasy_sports", label: "Фэнтези-спорт" },
  { value: "arcade_games", label: "Аркадные игры" },
];
